sonar.projectKey=onigoetz_i18n
sonar.organization=onigoetz
sonar.projectName=I18N
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,**/crafty.config.js,**/*.test.ts,**/benchmark-*/**
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=**/coverage/lcov.info
