name: benchmarks

on:
  push:
    branches:
      - "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Use Node.js 20.x
      uses: actions/setup-node@v5
      with:
        node-version: 22.x
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - name: Run benchmarks
      run: cd packages/benchmark-messageformat && node benchmark.js