name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn workspaces foreach -A --no-private run publish_to_npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
